# Generated by Django 6.0.5 on 2026-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizSystem', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Untitled Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=10),
        ),
    ]
